name: datn_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  get: ^4.6.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_secure_storage: ^9.2.2
  fl_chart: ^0.69.2
  salomon_bottom_bar: ^3.3.2
  ionicons: ^0.2.2
  shared_preferences: ^2.2.3
  jwt_decoder: ^2.0.1
  flutter_dropzone: ^4.0.2
  image_picker: ^1.1.2
  uri: ^1.0.0
  http: ^1.3.0
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.1.0
  logger: ^2.5.0
  intl: ^0.18.1
  http_parser: ^4.0.2
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  chewie: ^1.7.1
  video_player: ^2.9.1
  url_launcher: ^6.3.0
  flutter_slidable: ^3.1.2
  flutter_local_notifications: ^19.2.1
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  cupertino_icons: ^1.0.8
  mime:
  open_file: ^3.5.10
  path:
  flutter_pdfview:
  cached_video_player_plus: ^3.0.3
  async:
  dotted_border: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 

flutter:
  uses-material-design: true
  assets:
    - assets/logo/