// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA82RbBBzawm-scxj-fu-hPUrcv6TqjKw',
    appId: '1:982583803450:web:b3b94f7553994c31e7ff03',
    messagingSenderId: '982583803450',
    projectId: 'dormitorypushnoti',
    authDomain: 'dormitorypushnoti.firebaseapp.com',
    storageBucket: 'dormitorypushnoti.firebasestorage.app',
    measurementId: 'G-J29XZENTLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS1XAlhZ9CEKZsN65Ss0yFljf3Zwb_n-U',
    appId: '1:982583803450:android:a402b0a531c0cb5de7ff03',
    messagingSenderId: '982583803450',
    projectId: 'dormitorypushnoti',
    storageBucket: 'dormitorypushnoti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxKH9m4dxvKgzL1rOEwYjgCBQy5zzyiXU',
    appId: '1:982583803450:ios:8e02c96a5f4aaf4fe7ff03',
    messagingSenderId: '982583803450',
    projectId: 'dormitorypushnoti',
    storageBucket: 'dormitorypushnoti.firebasestorage.app',
    iosBundleId: 'com.example.datnApp',
  );

}